name: Code Quality

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  build:
    name: Build SvelteKit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
      - name: Create .env file
        run: | 
          echo "PUBLIC_SUPABASE_URL=${{ vars.SUPABASE_URL }}" >> .env
          echo "PUBLIC_SUPABASE_SERVICE_KEY=${{ vars.SUPABASE_KEY }}" >> .env
      - name: Check Formatters
        run: pnpm fmt
      - name: Run All Lints in Parallel
        run: pnpm lint
      - name: Build Website
        run: pnpm build
